menu/api/urls.py
from django.urls import include, path
from rest_framework import routers

from .views import RecipeViewSet

router = routers.SimpleRouter()
router.register('recipe', RecipeViewSet)
# router.register(r'recipe/(?P<reci_id>\d+)/comments',
#                 CommentViewSet,
#                 basename='comments')
# router.register('groups', GroupViewSet)
# router.register('follow', FollowViewSet, basename='follows')

urlpatterns = [
    path('', include(router.urls)),
    path('', include('djoser.urls')),
    path('', include('djoser.urls.jwt')),
]

menu/menu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('recipe.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include('api.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

menu/recipe/urls.py
from django.urls import path

from . import views

app_name = 'recipe'


urlpatterns = [
    path('', views.index, name='index'),
    path('recipe/create/', views.create_recipe, name='recipe_create'),
    path('recipe/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
]

menu/users/urls.py
from django.contrib.auth.views import LoginView, PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordChangeView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('logout/',
         views.logout,
         name='logout'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_token'),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'),
]

menu/core/models.py
from django.db import models


class CreatedModel(models.Model):
    """Абстрактная модель. Добавляет дату создания."""
    created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True
    )

    class Meta:
        abstract = True

menu/recipe/models.py
from django.db import models
from django.contrib.auth import get_user_model
from ckeditor.fields import RichTextField

from core.models import CreatedModel

User = get_user_model()


class Tag(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Recipe(CreatedModel):
    title = models.CharField(
        'Название',
        max_length=200
    )
    text = RichTextField(
        'Текст рецепта',
        help_text='Введите описание рецепта',
        blank=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='recipe'
    )
    # group = models.ForeignKey(
    #     Group,
    #     on_delete=models.SET_NULL,
    #     related_name='posts',
    #     blank=True,
    #     null=True,
    #     verbose_name='Группа',
    #     help_text='Группа, к которой будет относиться пост'
    # )
    tag = models.ManyToManyField(Tag, through='TagRecipe')
    image = models.ImageField(
        'Картинка',
        upload_to='recipe/',
        blank=True
    )
    cooking_time = models.IntegerField(
        'Время готовки'
    )

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title[:15]


class TagRecipe(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.tag} {self.recipe}'

menu/users/models.py
from django.db import models

# Create your models here.

menu/recipe/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

from .models import Recipe


class RecipeForm(forms.ModelForm):
    text = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Recipe
        fields = ('title',
                  'text',
                  'cooking_time',
                  'tag',
                  'image',)

    def clean_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise forms.ValidationError('Пост не можеть быть без текста!')
        return data

menu/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    first_name = forms.CharField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

menu/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, 'core/404.html', {'path': request.path}, status=404)


def server_error(request):
    return render(request, 'core/500.html', status=500)


def permission_denied(request, exception):
    return render(request, 'core/403.html', status=403)


def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')

menu/recipe/views.py
from dadata import Dadata
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect, get_object_or_404

from .forms import RecipeForm
from .models import Recipe, Tag, TagRecipe
from .utils import paginator

RECIPE_SHOW_LMT = 10


def index(request):
    recipe_list = Recipe.objects.all()
    tag_list = Tag.objects.all()
    recipe_tag_list = TagRecipe.objects.all()
    page_obj = paginator(request, recipe_list, RECIPE_SHOW_LMT)
    context = {
        'recipe_list': recipe_list,
        'tag_list': tag_list,
        'recipe_tag_list': recipe_tag_list,
        'page_obj': page_obj,
    }
    return render(request, 'recipe/api_index.html', context)


@login_required
def create_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()
            return redirect('recipe:index')
        return render(request, 'posts/create_recipe.html', {'form': form})
    form = RecipeForm()
    return render(request, 'recipe/create_recipe.html', {'form': form})


def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    # comments = post.comments.all()
    # form = CommentForm()
    context = {
        'recipe': recipe,
        # 'comments': comments,
        # 'form': form
    }
    return render(request, 'recipe/recipe_detail.html', context)

menu/users/views.py
from django.contrib import auth
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('recipe:index')
    template_name = 'users/signup.html'


def logout(request):
    auth.logout(request)
    return render(request, 'users/logged_out.html')

menu/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

menu/templates/includes/header.html
<nav id="nav-bar" class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    {% load static %}
    <a class="navbar-brand" href="{% url 'recipe:index' %}">
      <img class="mb-2" src="{% static 'img/logo.svg' %}" width="32" height="32">
      Food-List
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'recipe:index' %}active{% endif %}"
       href="{% url 'recipe:index' %}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"
       href="#">Блюда</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"
       href="#">Ингридиенты</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"
       href="{% url 'recipe:recipe_create' %}">Создать рецепт</a>
        </li>
        {% endwith %}
      </ul>
      <div class="d-flex">
        {% if request.user.is_authenticated %}
        <div class="dropdown">
          <a class="theme-text nav-link text-dark dropdown-toggle"
             href="#"
             role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{ user.get_full_name }}
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Профиль</a></li>
            <li><a class="dropdown-item" href="#"></a></li>
            <li><a class="dropdown-item" href="#">Профиль</a></li>
            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
          </ul>
        </div>
      </div>
      {% else %}
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% with request.resolver_match.view_name as view_name %}
            <li class="nav-item">
             <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}"
                href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}"
                 href="{% url 'users:signup' %}">Регистрация</a>
            </li>
        </ul>
          {% endwith %}
      {% endif %}
        <ul class="navbar-nav mt-1">
          <li class="nav-item">
            <div class="form-check form-switch mt-1">
              <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault" onchange="changeTheme(this.checked)">
            </div>
          </li>
          <li style="display: none" id="sun">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-moon" viewBox="0 0 16 16">
  <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278zM4.858 1.311A7.269 7.269 0 0 0 1.025 7.71c0 4.02 3.279 7.276 7.319 7.276a7.316 7.316 0 0 0 5.205-2.162c-.337.042-.68.063-1.029.063-4.61 0-8.343-3.714-8.343-8.29 0-1.167.242-2.278.681-3.286z"/>
</svg>
          </li>
          <li style="display: none" id="moon">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-brightness-high" viewBox="0 0 16 16">
  <path d="M8 11a3 3 0 1 1 0-6 3 3 0 0 1 0 6zm0 1a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
</svg>
          </li>
        </ul>

<script>

</script>
    </div>
  </div>
</nav>

menu/templates/recipe/create_recipe.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Последние обновления на сайте
{% endblock %}
{% block content %}
  <div class="container py-5">
            <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать рецепт
          {% else %}
            Новый рецепт
          {% endif %}
        </div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" enctype="multipart/form-data" action="
              {% if is_edit %}
<!--                {% url 'posts:post_edit' post.id %}-->
              {% else %}
                {% url 'recipe:recipe_create' %}
              {% endif %}">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% elif is_edit and field.label == 'Text' %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        Текст нового поста
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                        {% if is_edit %}
                          Сохранить
                        {% else %}
                          Добавить
                        {% endif %}
                    </button>
                  </div>
            </form>
          </div>
        </div>
      </div>
            </div>
  </div>
{% endblock %}

menu/templates/recipe/includes/recipe_list.html
{% load thumbnail %}
<article>
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-2 col-2">
        {% if recipe.image %}
            {% thumbnail recipe.image "300x300" crop="center" upscale=True as im %}
                <img class="card-img rounded img-fluid" src="{{ im.url }}">
              {% endthumbnail %}
          {% else %}
            {% load static %}
            <img class="card-img rounded img-fluid" src="{% static 'img/avatar.png' %}"
            width="150"
            height="150">
          {% endif %}
        <div class="d-flex flex-wrap mt-0 justify-content-around">
            <p class="m-0 text-center">
                {{ recipe.author.get_full_name}}
            </p>
        </div>
        <div class="d-flex flex-wrap mt-1 justify-content-around">
          <button type="button" class="btn btn-sm btn-outline-dark border-0 d-flex theme-btn" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Рейтинг">
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" stroke="black" fill="yellow" class="bi bi-star-fill" viewBox="0 0 16 16">
        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
        </svg>
              <p class="m-0">1111</p>
            </button>
          <button type="button" class="btn btn-sm btn-outline-dark border-0 d-flex theme-btn" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Рецепты">
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-journal-text" viewBox="0 0 16 16">
        <path d="M5 10.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
        <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
        <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
        </svg>
              <p class="m-0">
                            {% load user_filters %}
                  {{ recipe_list|count_author_things:recipe.author }}
              </p>
          </button>
        </div>
        </div>
        <div class="col-lg-10 col-md-10 col-sm-10 col-10">
        <div class="mt-0 mb-0 d-flex">
            <h4>
                {{ recipe.title }}
            </h4>
        </div>
        <div class="d-flex">
          <h5 class="m-1">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16">
                  <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
                  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/>
              </svg>
              <span class=" badge rounded-pill bg-dark">
                {{ recipe.cooking_time }} мин.
              </span>
          </h5>
          <h5 class="m-1">
              ₽
              <span class=" badge rounded-pill bg-danger">
                  ~400
              </span>
          </h5>
        </div>
            <div class="mt-0 mb-0 d-flex">
                {% if recipe|show_recipe_tags %}
            <p>
                {% load user_filters %}
                {% for tag in recipe|show_recipe_tags %}
                    <button class="btn btn-sm btn-dark badge rounded-pill">
                      {% load user_filters %}
                        #{{ tag }}
                    </button>
                {% endfor %}

            </p>
                {% endif %}
                {{ recipe_tag_list.recipe }}
        </div>
        <p class="mt-0 mb-0">
            {{ recipe.created }}
        </p>
        {% if recipe.group %}
            <p class="mt-0">
              Группа:
              <a href="{% url 'posts:group_list' post.group.slug %}" class="text-dark text-decoration-underline">
                {{ recipe.group.title }}
              </a>
            </p>
        {% endif %}
              <p class="mt-2">
        {% if recipe.text|length > 500 %}
          {{ recipe.text|slice:":1000"|safe }}...
        {% else %}
          {{ recipe.text|safe }}
        {% endif %}
        </p>
                  <a class="text-secondary" href="{% url 'recipe:recipe_detail' recipe.pk %}">
                      Подробнее...
                  </a>
        <a class="float-end text-dark text-decoration-none" href="#">
        <!--        {{ post.likes.count }}-->
        <!--        {% for like in post.likes.values %}-->
        <!--          {% if request.user.pk == like.user_id %}-->
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
            </svg>
          <div class="d-none">
        <!--          {% endif %}-->
        <!--        {% endfor %}-->
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="red" class="bi bi-heart" viewBox="0 0 16 16">
            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
          </svg>
        <!--            {% for like in post.likes.values %}-->
        <!--          {% if request.user.pk == like.user_id %}-->
          </div>
        <!--          {% endif %}-->
        <!--        {% endfor %}-->
        </a>
        </div>
    </div>
</article>

menu/templates/recipe/includes/tags_list.html
<button class="tag-btn btn btn-dark badge rounded-pill">
  {% load user_filters %}
    #{{ tag.name }} - {{ tag|count_tags }}
</button>

menu/templates/users/includes/card.html
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">{{ card_header }}</div>
      <div class="card-body"> <p>{{ card_body }}</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row --> 

menu/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %} 

menu/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Восстановление пароля завершено{% endblock %}
{% block content %}
{% load user_filters %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="{% url 'users:login' %}">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{% endblock %}

menu/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
</div>
{% endblock %} 